/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.realsense;

public class PXCBase {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PXCBase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PXCBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public SWIGTYPE_p_void QueryInstance(int cuid) {
    long cPtr = realsenseJNI.PXCBase_QueryInstance(swigCPtr, this, cuid);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void Release() {
    realsenseJNI.PXCBase_Release(swigCPtr, this);
  }

  public final static int CUID = realsenseJNI.PXCBase_CUID_get();

  public final static int WORKING_PROFILE = realsenseJNI.PXCBase_WORKING_PROFILE_get();

}
