/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.realsense;

public class PXCFaceModule extends PXCBase {
  private long swigCPtr;

  protected PXCFaceModule(long cPtr, boolean cMemoryOwn) {
    super(realsenseJNI.PXCFaceModule_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PXCFaceModule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PXCFaceConfiguration CreateActiveConfiguration() {
    long cPtr = realsenseJNI.PXCFaceModule_CreateActiveConfiguration(swigCPtr, this);
    return (cPtr == 0) ? null : new PXCFaceConfiguration(cPtr, false);
  }

  public PXCFaceData CreateOutput() {
    long cPtr = realsenseJNI.PXCFaceModule_CreateOutput(swigCPtr, this);
    return (cPtr == 0) ? null : new PXCFaceData(cPtr, false);
  }

}
