/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.realsense;

public class PXCHandModule extends PXCBase {
  private long swigCPtr;

  protected PXCHandModule(long cPtr, boolean cMemoryOwn) {
    super(realsenseJNI.PXCHandModule_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PXCHandModule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PXCHandConfiguration CreateActiveConfiguration() {
    long cPtr = realsenseJNI.PXCHandModule_CreateActiveConfiguration(swigCPtr, this);
    return (cPtr == 0) ? null : new PXCHandConfiguration(cPtr, false);
  }

  public PXCHandData CreateOutput() {
    long cPtr = realsenseJNI.PXCHandModule_CreateOutput(swigCPtr, this);
    return (cPtr == 0) ? null : new PXCHandData(cPtr, false);
  }

  public final static int CUID = realsenseJNI.PXCHandModule_CUID_get();

}
