/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.realsense;

public class PXCMetadata extends PXCBase {
  private long swigCPtr;

  protected PXCMetadata(long cPtr, boolean cMemoryOwn) {
    super(realsenseJNI.PXCMetadata_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PXCMetadata obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int QueryUID() {
    return realsenseJNI.PXCMetadata_QueryUID(swigCPtr, this);
  }

  public int QueryMetadata(int idx) {
    return realsenseJNI.PXCMetadata_QueryMetadata(swigCPtr, this, idx);
  }

  public pxcStatus DetachMetadata(int id) {
    return pxcStatus.swigToEnum(realsenseJNI.PXCMetadata_DetachMetadata(swigCPtr, this, id));
  }

  public pxcStatus AttachBuffer(int id, SWIGTYPE_p_unsigned_char buffer, int size) {
    return pxcStatus.swigToEnum(realsenseJNI.PXCMetadata_AttachBuffer(swigCPtr, this, id, SWIGTYPE_p_unsigned_char.getCPtr(buffer), size));
  }

  public int QueryBufferSize(int id) {
    return realsenseJNI.PXCMetadata_QueryBufferSize(swigCPtr, this, id);
  }

  public pxcStatus QueryBuffer(int id, SWIGTYPE_p_unsigned_char buffer, int size) {
    return pxcStatus.swigToEnum(realsenseJNI.PXCMetadata_QueryBuffer(swigCPtr, this, id, SWIGTYPE_p_unsigned_char.getCPtr(buffer), size));
  }

  public pxcStatus AttachSerializable(int id, PXCBase instance) {
    return pxcStatus.swigToEnum(realsenseJNI.PXCMetadata_AttachSerializable(swigCPtr, this, id, PXCBase.getCPtr(instance), instance));
  }

  public pxcStatus CreateSerializable(int id, int cuid, SWIGTYPE_p_p_void instance) {
    return pxcStatus.swigToEnum(realsenseJNI.PXCMetadata_CreateSerializable(swigCPtr, this, id, cuid, SWIGTYPE_p_p_void.getCPtr(instance)));
  }

  public final static int CUID = realsenseJNI.PXCMetadata_CUID_get();

}
