/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.realsense;

public class PXCPointI32 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PXCPointI32(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PXCPointI32 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        realsenseJNI.delete_PXCPointI32(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(int value) {
    realsenseJNI.PXCPointI32_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return realsenseJNI.PXCPointI32_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    realsenseJNI.PXCPointI32_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return realsenseJNI.PXCPointI32_y_get(swigCPtr, this);
  }

  public PXCPointI32() {
    this(realsenseJNI.new_PXCPointI32(), true);
  }

}
