/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.realsense;

public final class pxcStatus {
  public final static pxcStatus PXC_STATUS_NO_ERROR = new pxcStatus("PXC_STATUS_NO_ERROR", realsenseJNI.PXC_STATUS_NO_ERROR_get());
  public final static pxcStatus PXC_STATUS_FEATURE_UNSUPPORTED = new pxcStatus("PXC_STATUS_FEATURE_UNSUPPORTED", realsenseJNI.PXC_STATUS_FEATURE_UNSUPPORTED_get());
  public final static pxcStatus PXC_STATUS_PARAM_UNSUPPORTED = new pxcStatus("PXC_STATUS_PARAM_UNSUPPORTED", realsenseJNI.PXC_STATUS_PARAM_UNSUPPORTED_get());
  public final static pxcStatus PXC_STATUS_ITEM_UNAVAILABLE = new pxcStatus("PXC_STATUS_ITEM_UNAVAILABLE", realsenseJNI.PXC_STATUS_ITEM_UNAVAILABLE_get());
  public final static pxcStatus PXC_STATUS_HANDLE_INVALID = new pxcStatus("PXC_STATUS_HANDLE_INVALID", realsenseJNI.PXC_STATUS_HANDLE_INVALID_get());
  public final static pxcStatus PXC_STATUS_ALLOC_FAILED = new pxcStatus("PXC_STATUS_ALLOC_FAILED", realsenseJNI.PXC_STATUS_ALLOC_FAILED_get());
  public final static pxcStatus PXC_STATUS_DEVICE_FAILED = new pxcStatus("PXC_STATUS_DEVICE_FAILED", realsenseJNI.PXC_STATUS_DEVICE_FAILED_get());
  public final static pxcStatus PXC_STATUS_DEVICE_LOST = new pxcStatus("PXC_STATUS_DEVICE_LOST", realsenseJNI.PXC_STATUS_DEVICE_LOST_get());
  public final static pxcStatus PXC_STATUS_DEVICE_BUSY = new pxcStatus("PXC_STATUS_DEVICE_BUSY", realsenseJNI.PXC_STATUS_DEVICE_BUSY_get());
  public final static pxcStatus PXC_STATUS_EXEC_ABORTED = new pxcStatus("PXC_STATUS_EXEC_ABORTED", realsenseJNI.PXC_STATUS_EXEC_ABORTED_get());
  public final static pxcStatus PXC_STATUS_EXEC_INPROGRESS = new pxcStatus("PXC_STATUS_EXEC_INPROGRESS", realsenseJNI.PXC_STATUS_EXEC_INPROGRESS_get());
  public final static pxcStatus PXC_STATUS_EXEC_TIMEOUT = new pxcStatus("PXC_STATUS_EXEC_TIMEOUT", realsenseJNI.PXC_STATUS_EXEC_TIMEOUT_get());
  public final static pxcStatus PXC_STATUS_FILE_WRITE_FAILED = new pxcStatus("PXC_STATUS_FILE_WRITE_FAILED", realsenseJNI.PXC_STATUS_FILE_WRITE_FAILED_get());
  public final static pxcStatus PXC_STATUS_FILE_READ_FAILED = new pxcStatus("PXC_STATUS_FILE_READ_FAILED", realsenseJNI.PXC_STATUS_FILE_READ_FAILED_get());
  public final static pxcStatus PXC_STATUS_FILE_CLOSE_FAILED = new pxcStatus("PXC_STATUS_FILE_CLOSE_FAILED", realsenseJNI.PXC_STATUS_FILE_CLOSE_FAILED_get());
  public final static pxcStatus PXC_STATUS_DATA_UNAVAILABLE = new pxcStatus("PXC_STATUS_DATA_UNAVAILABLE", realsenseJNI.PXC_STATUS_DATA_UNAVAILABLE_get());
  public final static pxcStatus PXC_STATUS_DATA_NOT_INITIALIZED = new pxcStatus("PXC_STATUS_DATA_NOT_INITIALIZED", realsenseJNI.PXC_STATUS_DATA_NOT_INITIALIZED_get());
  public final static pxcStatus PXC_STATUS_INIT_FAILED = new pxcStatus("PXC_STATUS_INIT_FAILED", realsenseJNI.PXC_STATUS_INIT_FAILED_get());
  public final static pxcStatus PXC_STATUS_STREAM_CONFIG_CHANGED = new pxcStatus("PXC_STATUS_STREAM_CONFIG_CHANGED", realsenseJNI.PXC_STATUS_STREAM_CONFIG_CHANGED_get());
  public final static pxcStatus PXC_STATUS_POWER_UID_ALREADY_REGISTERED = new pxcStatus("PXC_STATUS_POWER_UID_ALREADY_REGISTERED", realsenseJNI.PXC_STATUS_POWER_UID_ALREADY_REGISTERED_get());
  public final static pxcStatus PXC_STATUS_POWER_UID_NOT_REGISTERED = new pxcStatus("PXC_STATUS_POWER_UID_NOT_REGISTERED", realsenseJNI.PXC_STATUS_POWER_UID_NOT_REGISTERED_get());
  public final static pxcStatus PXC_STATUS_POWER_ILLEGAL_STATE = new pxcStatus("PXC_STATUS_POWER_ILLEGAL_STATE", realsenseJNI.PXC_STATUS_POWER_ILLEGAL_STATE_get());
  public final static pxcStatus PXC_STATUS_POWER_PROVIDER_NOT_EXISTS = new pxcStatus("PXC_STATUS_POWER_PROVIDER_NOT_EXISTS", realsenseJNI.PXC_STATUS_POWER_PROVIDER_NOT_EXISTS_get());
  public final static pxcStatus PXC_STATUS_CAPTURE_CONFIG_ALREADY_SET = new pxcStatus("PXC_STATUS_CAPTURE_CONFIG_ALREADY_SET", realsenseJNI.PXC_STATUS_CAPTURE_CONFIG_ALREADY_SET_get());
  public final static pxcStatus PXC_STATUS_TIME_GAP = new pxcStatus("PXC_STATUS_TIME_GAP", realsenseJNI.PXC_STATUS_TIME_GAP_get());
  public final static pxcStatus PXC_STATUS_PARAM_INPLACE = new pxcStatus("PXC_STATUS_PARAM_INPLACE", realsenseJNI.PXC_STATUS_PARAM_INPLACE_get());
  public final static pxcStatus PXC_STATUS_DATA_NOT_CHANGED = new pxcStatus("PXC_STATUS_DATA_NOT_CHANGED", realsenseJNI.PXC_STATUS_DATA_NOT_CHANGED_get());
  public final static pxcStatus PXC_STATUS_PROCESS_FAILED = new pxcStatus("PXC_STATUS_PROCESS_FAILED", realsenseJNI.PXC_STATUS_PROCESS_FAILED_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static pxcStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + pxcStatus.class + " with value " + swigValue);
  }

  private pxcStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private pxcStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private pxcStatus(String swigName, pxcStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static pxcStatus[] swigValues = { PXC_STATUS_NO_ERROR, PXC_STATUS_FEATURE_UNSUPPORTED, PXC_STATUS_PARAM_UNSUPPORTED, PXC_STATUS_ITEM_UNAVAILABLE, PXC_STATUS_HANDLE_INVALID, PXC_STATUS_ALLOC_FAILED, PXC_STATUS_DEVICE_FAILED, PXC_STATUS_DEVICE_LOST, PXC_STATUS_DEVICE_BUSY, PXC_STATUS_EXEC_ABORTED, PXC_STATUS_EXEC_INPROGRESS, PXC_STATUS_EXEC_TIMEOUT, PXC_STATUS_FILE_WRITE_FAILED, PXC_STATUS_FILE_READ_FAILED, PXC_STATUS_FILE_CLOSE_FAILED, PXC_STATUS_DATA_UNAVAILABLE, PXC_STATUS_DATA_NOT_INITIALIZED, PXC_STATUS_INIT_FAILED, PXC_STATUS_STREAM_CONFIG_CHANGED, PXC_STATUS_POWER_UID_ALREADY_REGISTERED, PXC_STATUS_POWER_UID_NOT_REGISTERED, PXC_STATUS_POWER_ILLEGAL_STATE, PXC_STATUS_POWER_PROVIDER_NOT_EXISTS, PXC_STATUS_CAPTURE_CONFIG_ALREADY_SET, PXC_STATUS_TIME_GAP, PXC_STATUS_PARAM_INPLACE, PXC_STATUS_DATA_NOT_CHANGED, PXC_STATUS_PROCESS_FAILED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

