/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.realsense;

public class realsense implements realsenseConstants {
  public static PXCSession PXCSession_Create() {
    long cPtr = realsenseJNI.PXCSession_Create();
    return (cPtr == 0) ? null : new PXCSession(cPtr, false);
  }

}
