/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.realsense;

public interface realsenseConstants {
  public final static int PXC_VERSION_MAJOR = realsenseJNI.PXC_VERSION_MAJOR_get();
  public final static int PXC_VERSION_MINOR = realsenseJNI.PXC_VERSION_MINOR_get();
  public final static int PXC_VERSION_BUILD = realsenseJNI.PXC_VERSION_BUILD_get();
  public final static int PXC_VERSION_REVISION = realsenseJNI.PXC_VERSION_REVISION_get();
}
