/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.realsense;

public class realsenseJNI {
  public final static native int PXC_VERSION_MAJOR_get();
  public final static native int PXC_VERSION_MINOR_get();
  public final static native int PXC_VERSION_BUILD_get();
  public final static native int PXC_VERSION_REVISION_get();

	static {
		new com.badlogic.gdx.utils.SharedLibraryLoader().load("gdx-realsense");
	}

}
